### ISSUE TITLE
Making the code work

### ISSUE THREAD

**Issue by mhdtbc** [ownport/wireshark-pytools#5]
Dear @ownport ,

I found your code today, and i'm very grateful that you happen to tackle this problem.
I'm trying to make your script work, i tried with python3 but i couldn't make it work for a given trace in which i have a lot of SCTP bundled packets.

I have an empty file :

Output format: pcap
Read 0 potential packets, wrote 0 packets (24 bytes).

would you please indicate to me if there is a newer version of this code ?

Thank you very much for any help given on this subject.

**Comment by ownport** [comment]
Sorry but I'm going to archive the project. It was designed for py2 and I don't have plans to support it for py3. So you can fork it and adopt for your needs
